plugins:
  - name: hardhat     # For running simulations
  - name: etherscan   # For getting contract types
  - name: alchemy     # For greater access to transactions and fork mode
  - name: keyring     # For storing parity URI and Alchemy API key

keyring:
  # Makes secrets readable in plugins
  set_env_vars: true

ethereum:
  # Use fork mode for access to wide range of txns
  default_network: mainnet-fork
  local:
    default_provider: hardhat
  mainnet:
    default_provider: alchemy

solidity:
  # For debugging compiler logic
  optimize: false
